server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
     name: PRODUCT-SERVICE    
  config:
     import: configserver:http://localhost:9004   

#eureka:
#   client:
 #     fetch-registry: true
 #     register-with-eureka: true
#      service-url:
 #        defaultZone: http://localhost:8761/eureka
 #  instance:
 #     prefer-ip-address: true   
      
  